astrolabsoftware/fink-science-portal

- apps/plotting.py
- apps/summary.py
- apps/utils.py
This PR adds upper limits to the lightcurve. This is available only for difference magnitude.
> Add upper limits in lightcurve (difference magnitude)

- apps/explorer.py
This PR adds a reset button to the explorer page to clear all fields.
> Reset button

- apps/explorer.py
> capitalize Simbad class name before sorting

- apps/utils.py
> Add a limit on ndethist<20 for early SNe class

- apps/explorer.py
> Separate labels and values for simbad types

- apps/explorer.py
> Trigger the query only if the reset button is not pressed.

- apps/plotting.py
> Update hover to display MJD value

- apps/__init__.py
All issues and PR listed here: https://github.com/astrolabsoftware/fink-science-portal/milestone/1?closed=1
Main highlights:
- Update alert classification (with addition of Early SN candidate)
- Update cutouts when clicking on a lightcurve point
- Add upper limits measurements in lightcurve
- Improve microlensing fit by using pyLIMA
- Extend the representation of different coordinates formats for the conesearch
- Improved layout (view, hover, reset button, documentation)
- Many bug fixes!
Thanks to all users and contributors for their feedback!
> Bump Portal version to 0.2

- apps/utils.py
> Fix typo in the mulens class name

- apps/cards.py
- apps/home.py
- apps/xmatch.py
- assets/home.css
- index.py
You can now upload a catalog, and perform a xmatch against all Fink data (more than 60 million alerts processed so far). Enjoy!!!!
> New service: xmatch

- apps/plotting.py
> Fix correct magnitude for microlensing fit

- apps/plotting.py
> Fix index if r is the only band

- apps/api.py
- assets/fink_types.csv
- index.py
This PR brings online the public API
| HTTP Method | URI | Action | Availability |
|-------------|-----|--------|--------------|
| POST/GET | http://134.158.75.151:24000/api/v1/objects| Retrieve single object data from the Fink database | &#x2611;&#xFE0F; |
| POST/GET | http://134.158.75.151:24000/api/v1/explorer | Query the Fink alert database | &#x2611;&#xFE0F; |
| POST/GET | http://134.158.75.151:24000/api/v1/latests | Get latest alerts by class | &#x2611;&#xFE0F; |
| POST/GET | http://134.158.75.151:24000/api/v1/xmatch | Cross-match user-defined catalog with Fink alert data| &#x274C; |
| GET  | http://134.158.75.151:24000/api/v1/classes  | Display all Fink derived classification | &#x2611;&#xFE0F; |
- The xmatch service is not yet available through the API
- One cannot yet choose …
> public API

- apps/api.py
- apps/explorer.py
> Fix digits for conesearch example

- apps/explorer.py
> Give possibility to add additional columns in explorer results

- apps/api.py
- apps/explorer.py
This PR mainly adds a new service in the API to display alert fields (name, type, and description):
http://134.158.75.151:24000/api/v1/columns
> Update explorer doc & add new service to display available alert fields

- apps/api.py
- apps/cards.py
- apps/explorer.py
- apps/plotting.py
- apps/summary.py
We now use directly API calls inside the explorer tab 🎉
> Bring the API in the core of explorer

- apps/plotting.py
> Update layout (plot legends)

- apps/cards.py
This PR adds a button to perform a cross-match in the ASAS-SN catalogues of Variable stars. It is the first step towards automatic classification of variable stars.
> Cross-match: Search in ASAS-SN Catalogues of Variable stars

- apps/cards.py
- apps/plotting.py
- apps/summary.py
> Interactive Fink probabilities for each point in the light curve

- apps/cards.py
> Add link to open astronomy catalog

- apps/__init__.py
- index.py
All issues and PR listed here: https://github.com/astrolabsoftware/fink-science-portal/milestone/3?closed=1
Main highlights:
- Add new service Fink Xmatch
- Add API (see also https://github.com/astrolabsoftware/fink-science-portal/milestone/2?closed=1)
- Give possibility to add dynamically additional columns in explorer results
- Add color evolution (r-g and its rate) in the explorer page
- Interactive link between lightcurve and cutouts, and between lightcurve and ML scores
- External links to ASAS-SN and Open Astronomy Catalog
- Many bug and layout fixes!
Thanks to all users and contributors for their feedback!
> Bump version to 0.3

- apps/__init__.py
All issues and PR listed here: https://github.com/astrolabsoftware/fink-science-portal/milestone/4?closed=1
Main highlights:
- Provide xmatch in the explorer page
- Add dynamically columns in explorer
- Large refactoring of explorer
- Color code catalogs in the skymap
- Many bug and layout fixes!
Thanks to all users and contributors for their feedback!
> Bump to 0.4

- apps/explorer.py
> Fix bug in the alert display

- apps/plotting.py
Add new normalizer for the cutouts based on sigmoid function. Replace the old normalizer based on the central pixel of the cutouts
> cutout_plotting_improvement

- apps/cards.py
See #116 -- the new TNS URL is now https://www.wis-tns.org/search
> Fix new TNS URL

- apps/cards.py
- apps/plotting.py
- apps/summary.py
See #126 and https://github.com/astrolabsoftware/fink-broker/issues/423
> Display valid measurements contained in history

- apps/api.py
- apps/cards.py
- apps/explorer.py
- apps/utils.py
- apps/xmatch.py
- assets/fink_types.csv
> Update the portal with Kilonova search

- apps/cards.py
- apps/plotting.py
#14 -- now the title of the plot will give the fitted period, and a score for the fit. The score is between 0 (poor fit) and 1 (excellent fit).
> Add score to variable star fit

- apps/cards.py
- apps/plotting.py
To ease the comparison with scores, the units for the lightcurve is DC magnitude. Closes #113
> [SN] Fix the units to DC mag

- apps/api.py
- apps/cards.py
- apps/explorer.py
- apps/plotting.py
- apps/utils.py
This PR updates a number  of things related to supernova:
- Add explanation of SN classifiers, and how we classify candidates #124 
- Add graph for color evolution, and other color quantities #15 (g-r, delta(g), delta(r), and rates)
- Speed up queries that do not need color evolution #99 (not resolving it yet!)
- rename `r-g` into `g-r`
Note that now queries like:
```python
t0 = time.time()
'http://134.158.75.151:24000/api/v1/explorer',
json={
'startdate': '2019-11-03 02:40:00',
'window': '10'
}
)
print('API', time.time() - t0)
```
> [Supernova] Various updates

- README.md
See full log at https://github.com/astrolabsoftware/fink-science-portal/milestone/5?closed=1
> Bump to version 0.5

- apps/api.py
> Remove color computation for SSO

- index.py
> Add link to API tutorials in the navbar

- apps/explorer.py
@dturpin-svom now you can see the number of alerts in the legend :-)
> Add number of alerts in the legend of the skymap

- apps/api.py
- apps/cards.py
- apps/explorer.py
- apps/plotting.py
- apps/utils.py
- assets/fink_types.csv
- assets/simbad_types.csv
Note, we need to wait for #156 to finalise the move (in the database, it is still `Early SN candidate`).
> Rename Early SN candidate into Early SN Ia candidate

- apps/utils.py
> Update the condition on microlensing

- apps/plotting.py
> Remove hover for figure

- apps/__init__.py
https://github.com/astrolabsoftware/fink-science-portal/milestone/6?closed=1
> Bump to 0.6

- apps/utils.py
> Remove jdstarthist from the Early SN candidate class

- apps/utils.py
> Remove MPC objects and 1st detection for SN detection

- apps/api.py
- apps/explorer.py
- apps/utils.py
> Update conesearch frontend 

- apps/__init__.py
https://github.com/astrolabsoftware/fink-science-portal/milestone/8?closed=1
> Bump to 0.7

- apps/explorer.py
- index.py
> Fix wrong redirection and remove explorer

- apps/api.py
> Fix when window_days_conesearch is None

- apps/summary.py
- index.py
> Web application

- apps/__init__.py
https://github.com/astrolabsoftware/fink-science-portal/milestone/9?closed=1
Major change:
- The explorer page is now the home page
- The Science Portal is now available on mobile platforms
> Bump to 0.8

- apps/api.py
- index.py
> Fix typo when calling API layout

- index.py
> Open table result in the same frame for mobile application

- apps/api.py
- apps/cards.py
- apps/utils.py
- index.py
Closes #196 
This PR adds the new added value `v:constellation`.
> Add information about constellation

- apps/summary.py
> Update the documentation for alert properties table

- index.py
> Return empty table if no results instead of full container

- apps/__init__.py
See https://github.com/astrolabsoftware/fink-science-portal/milestone/10?closed=1
> Bump to 0.9

- apps/api.py
- index.py
> Update documentation with more recent data

- apps/__init__.py
See https://github.com/astrolabsoftware/fink-science-portal/milestone/11
> Bump to 0.10

- apps/api.py
> Add a mask to not double count valid measurement in bad quality ones

- apps/api.py
> [Bug] Add condition when removing duplicates

- apps/plotting.py
- apps/statistics.py
See https://github.com/astrolabsoftware/fink-science-portal/pull/233#issuecomment-984129459
What is new:
- enclose the daily stats in the header
- [daily] make title more descriptive, and add popover with help
- [daily] add percentage
- [timeline] add percentage
> Feedback for the statistics page

- apps/__init__.py
https://github.com/astrolabsoftware/fink-science-portal/milestone/12?closed=1
> Bump to 0.11

- apps/plotting.py
Thanks for the feedback @aboucaud !
> Make transparent the background for histograms

- apps/api.py
- apps/cards.py
- apps/plotting.py
- apps/statistics.py
- apps/utils.py
- index.py
> Update the classification & load new schema

- apps/summary.py
> Ship bug fix for non-tracklet objects

- apps/cards.py
- apps/plotting.py
- assets/home.css
Layout has been improved:
- cutouts rounded, and animated (zoom)
- information wrapped in accordions
- radio items replaced by chips
- various documentation improvements
> Improve layout

- apps/cards.py
> Update the link to JPL

- apps/plotting.py
This PR fixes the heatmap display (last year was not properly displayed).
Closes #265
> Update heatmap display

- apps/cards.py
- apps/plotting.py
- apps/summary.py
> [SSO] Add HG12 & HG fitting functions

- apps/__init__.py
Minor release, containing mostly new functionalities for SSO science. Full log at: https://github.com/astrolabsoftware/fink-science-portal/milestone/7?closed=1
> Bump to 1.1

- apps/api.py
- apps/plotting.py
- apps/summary.py
- apps/utils.py
> Handle SSO objects with temporary designation

- apps/utils.py
> Fix query formatting

- apps/utils.py
> Fix bug with SSO url search

- apps/plotting.py
> Remove wrong formatting in the Timelines

- apps/api.py
- tests/api_classsearch_test.py
> Add possibility to filter columns when querying for classes

- apps/statistics.py
> Bring back basic:raw in the game

- index.py
- tests/api_bayestar_test.py
Closes #312 
Finally there! Enter your query (ZTF ID, conesearch, etc.), and just press enter to see the result...
> Enable enter key to submit a query

- apps/summary.py
- apps/utils.py
- requirements.txt
> Add QR codes for objects

- index.py
> Add button to group results by SSO & tracklets

- app.py
- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- tests/api_ssocand_test.py
> [API] Enpoint for SSO candidates

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- apps/utils.py
- tests/api_sso_test.py
> Enable query with several SSO names at once

- apps/api/utils.py
- tests/api_stats_test.py
> Fix stats API when submitting column names

- apps/api/api.py
> Update API documentation

- apps/utils.py
Closes #337 
Add a 15 second shift when computing ephemerides to account to the exposure time
> [SSO] correct astrometry residual

- app.py
- config.yml
- index.py
> Externalise configuration

- README.md
- docker/Dockerfile
Closes #342 
This docker file is for internal use only, as one needs access to the HBase cluster.
> Initial docker file

- app.py
- apps/__init__.py
- apps/api/api.py
- apps/cards.py
- apps/plotting.py
- apps/statistics.py
- apps/summary.py
- assets/home.css
- index.py
- requirements.txt
Version 2 for the Portal. This includes Dash v2, but also using Dash Mantine components extensively. 
https://fink-broker.org/2022-08-30-science-portal-updates/
The performance is also better, but more is to come.
> Science Portal v2

- apps/cards.py
- apps/plotting.py
- Display residuals wrt the mean position
- Display coordinates in ecliptic and galactic
> bring back coordinates information

- apps/statistics.py
- tests/api_sso_test.py
> Fix NaN in class:Unknown

- apps/cards.py
> Fix name of the chips for coordinate

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
> Update Fink-fat column name

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- apps/summary.py
- tests/api_ssocand_test.py
> Better error message for non-existent objects

- apps/api/utils.py
- tests/api_ssocand_test.py
> [API] Fix bugs that prevented users to select a particular ssoCandId 

- apps/api/api.py
- apps/statistics.py
- apps/summary.py
- assets/home.css
- index.py
#376 
- Loading message
- Updated & dimmer background
> Layout part 1

- index.py
The old navbar (fixed, top) is now replaced by a drawer (left).
> New navigation bar

- apps/query_cluster.py
> [Data transfer] Open links in another tab

- apps/query_cluster.py
> Swap accordion items

- apps/query_cluster.py
> Mobile version for the datatransfer service

- apps/query_cluster.py
- assets/spark_transfer.py
> [Data transfer] Add new modules

- apps/summary.py
> Fix broken mobile version

- assets/spark_elasticc_transfer.py
> Correct path discovery for ELASTiCC

- assets/spark_elasticc_transfer.py
- assets/spark_ztf_transfer.py
> Set Kafka partitions to 10

- apps/api/doc.py
> Update documentation for bayestar use

- apps/api/api.py
- apps/api/utils.py
> Enable color to be extracted

- apps/plotting.py
- apps/summary.py
- apps/utils.py
- apps/varstars/cards.py
- apps/varstars/plotting.py
- requirements.txt
> Improve dc_mag and update SSO computation

- apps/api/doc.py
> Update doc for GW

- apps/sso/cards.py
> [SSOCARD] Replace space by underscore

- apps/summary.py
> Resolve name before querying miriade

- apps/query_cluster.py
- assets/spark_elasticc_transfer.py
- assets/spark_ztf_transfer.py
> Update schema generation for the data transfer service

- apps/api/utils.py
> Sanitize cutouts before normalising

- apps/api/utils.py
- apps/gw.py
> [bug] Fix callback for GW service

- index.py
> Update aladin visualisation for conesearch output

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- tests/api_bayestar_test.py
```python
'https://fink-portal.org/api/v1/bayestar',
json={
'event_name': 'S230709bi',
'credible_level': credible_level,
'output-format': 'json'
}
)
```
works.
> [GW]  Add a new argument to query directly GraceDB 

- apps/gw.py
- apps/utils.py
Now we can query the portal using URL, e.g.
```
https://fink-portal.org/gw?credible_level=0.2&event_name=S230709bi
```
> [GW] URL search

- apps/api/api.py
- apps/api/utils.py
> Resolver: set the reverse argument as boolean

- assets/spark_ztf_transfer.py
Features were introduced in 2023, and previous alert packets do not contain features which makes the Data Transfer job to crash.
> [Data Transfer] Compute features on-the-fly for historical data

- apps/plotting.py
> Update date formatting for the statistics

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- tests/api_ssoft_test.py
> [SSO] enable version and flavor for the SSOFT

- apps/sso/cards.py
> Update syntax for rocks

- assets/spark_ztf_transfer.py
> Add features in the lightcurve option

- apps/api/api.py
- apps/api/utils.py
- requirements.txt
Closes #502 
This PR introduces the endpoint to upload Euclid SSO data into Fink. Currently, it only reads data, but does not store it in HBase.
> [Euclid] Initial endpoint

- apps/gw.py
- apps/plotting.py
> Add coordinates in hms dms

- apps/cards.py
> Fix TNS classification

- app.py
- apps/api/utils.py
- apps/utils.py
- tests/api_random_object_test.py
- tests/api_resolver_test.py
> Update HBase client

- apps/api/doc.py
- apps/utils.py
- tests/api_anomaly_test.py
> Cast features into string array

- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- tests/api_ssocand_test.py
> Add a new argument in /ssocand to control the max number of entries

- tests/api_resolver_test.py
- tests/api_ssocand_test.py
> Continuous integration: data evolved!

- apps/query_cluster.py
> Update documentation for Data Transfer

- apps/api/utils.py
- tests/api_resolver_test.py
> Make the TNS and SSO resolver case-insensitive

- apps/api/doc.py
- apps/api/utils.py
- tests/api_resolver_test.py
> Enable choosing the number of rows to return for the TNS table download

- apps/sso/cards.py
- requirements.txt
> Use formatted form for SSO

- apps/utils.py
Should significantly improve #100 
Details at https://github.com/astrolabsoftware/fink-science-portal/issues/100#issuecomment-1899468788
> Optimize access to HBase scan results

- requirements.txt
- tests/api_ssoft_test.py
Closes #563 
Update test for SSOFT and update fink-spins version on the server
> Update test for SSOFT

- apps/plotting.py
- apps/statistics.py
- apps/utils.py
> Fix wrong display in statistics because the DataFrame was not sorted

- apps/cards.py
- apps/plotting.py
- apps/utils.py
- assets/theme.css
- index.py
- requirements.txt
...plus some minor cleanups.
Mostly fixes #562 , except for historical classifications and TNS badges that are not available in search results / card views
> Generalization of badges for summary and card views

- app.py
- apps/gw.py
- apps/plotting.py
- index.py
> Aladin Lite v3

- apps/cards.py
- apps/utils.py
- apps/varstars/cards.py
Closes #561 
In addition, we now mutualise the buttons creation to ease their re-use (`apps.utils.create_button_for_external_conesearch`)
> Add VSX conesearch in the variable star profile

- apps/gw.py
> Remove trailing z in gw.py

- apps/parse.py
> Make the ZTF prefix case insensitive for object query

- apps/utils.py
> Drop erroneous spicy_name column if it exists

- apps/utils.py
- apps/varstars/cards.py
> Split ASAS-SN general photometry and variable

- apps/plotting.py
> Update oblateness threshold from 0.1 to 0.3

- app.py
> Freeze the Aladin version to 3.2.0

- apps/gw.py
- apps/plotting.py
- index.py
> Revert colors to Panstarrs DR1 color-z-zg-g

- requirements.txt
Closes #616 
See also https://github.com/maxmahlke/rocks/issues/36
> Bump rocks to 1.9.8

- .github/workflows/linter.yml
- .ruff.toml
- app.py
- apps/about.py
- apps/api/api.py
- apps/api/doc.py
- apps/api/utils.py
- apps/cards.py
- apps/client.py
- apps/euclid/utils.py
- apps/gw.py
- apps/mining/utils.py
- apps/mulens/cards.py
- apps/parse.py
- apps/plotting.py
- apps/query_cluster.py
- apps/sso/cards.py
- apps/statistics.py
- apps/summary.py
- apps/supernovae/cards.py
- apps/utils.py
- apps/varstars/cards.py
- index.py
- requirements.txt
- telemetry.py
> Lint & reformat with Ruff

- .github/workflows/run_test.yml
> Use Python 3.11 for the test suite

- apps/summary.py
> Fix bug when loading tracklet data

- apps/plotting.py
- tests/api_single_object_test.py
> Update heatmap colorscale

- apps/sso/cards.py
> Fix bug when displaying comet data

- apps/query_cluster.py
Closes #650 
It turns out that the `dmc.MultiSelect` component takes only strings as values...
https://www.dash-mantine-components.com/components/multiselect
> Fix bug in the value type required by selector

- apps/sso/cards.py
Closes #658 
cc: @colinorionchandler
> Use ssnamenr instead of name from Rocks

- apps/summary.py
- requirements.txt
> Remove offending lines preventing SSO data to be downloaded

- apps/query_cluster.py
> Revert wrong cast

- apps/plotting.py
- apps/sso/cards.py
> SSO: various updates

- apps/api/api.py
- apps/api/utils.py
- apps/sso/cards.py
- apps/sso/utils.py
- apps/summary.py
- apps/utils.py
- requirements.txt
- tests/api_sso_test.py
> Expose residuals from the SSO API (sHG1G2 model)

- apps/api/utils.py
- apps/sso/cards.py
- apps/summary.py
- tests/api_sso_test.py
> Add residuals when downloading SSO data

- apps/summary.py
> Open SSO tab if the object is a SSO

- apps/api/api.py
- apps/api/utils.py
- apps/utils.py
- requirements.txt
- tests/api_cutouts_test.py
- tests/api_single_object_test.py
- tests/api_ssoft_test.py
> New mechanism to download cutouts

- apps/plotting.py
> Fix range for cutouts

- app.py
- apps/plotting.py
> Check that undefined are not present, otherwise block the update

- apps/summary.py
- index.py
> Remove the allclasses option

- apps/plotting.py
- apps/summary.py
> Update H bounds

- apps/__init__.py
- apps/gw.py
- apps/summary.py
- apps/utils.py
- requirements.txt
> v6: various bugs

- index.py
> Fix JSON decoding when constructing the list of fields

- index.py
> Add trend keyword

- assets/spark_ztf_transfer.py
> Update import for data transfer

- assets/spark_ztf_transfer.py
- requirements.txt
> Bump to fink-filters v6

- apps/plotting.py
- apps/summary.py
- requirements.txt
> Add sfHG1G2 model

- apps/plotting.py
- apps/summary.py
> Remove combined photometry for phase curve moduling

- apps/parse.py
- index.py
This PR adds two change:
- Closes #718 
- Closes #739
> Search bar updates

- apps/cards.py
- apps/observability/cards.py
- apps/observability/utils.py
- apps/summary.py
- assets/spark_elasticc_transfer.py
- assets/spark_ztf_transfer.py
Closes #745 
CMO added for the PoC
@emilleishida
> Add the possibility tor register new observatories for observability 

- apps/observability/cards.py
- apps/observability/utils.py
- apps/plotting.py
- apps/summary.py
Closes #748
Adds a roll-down menu for custom observatories obtained by filling Longitude and Latitude of the wanted observatory.
TODO:
> Custom observatory from coordinates

- apps/cards.py
> Use GET for /metadata

- apps/xmatch.py
Closes #764 
Interpretation of coordinates is borrowed from the search bar parser. I need to refactor this in one single place later.
> Force decimal degree conversion

- apps/cards.py
- apps/summary.py
The pattern matched input is a list with variable number of elements (how many ids are matched), the output is supposed to be the same size (as we are using the same elements). I don't know whether there is an "official" way to broadcast single value to many elements, so l implemented it using that fact.
> Use pattern matching to properly handle both DR photometry buttons

- assets/spark_ztf_transfer.py
- assets/spark_ztf_xmatch.py
> Enforce proper serialisation of fields

- apps/plotting.py
Fix for the problem of difference flux being displayed as always positive in #767 (alerts only, DR flux is ok)
> Apply proper sign to differential flux

- apps/xmatch.py
- assets/spark_ztf_xmatch.py
> Force tnsclass to replace tns column
