astrolabsoftware/fink-science-portal

apps/explorer.py, apps/utils.py
This PR brings a new approach to label alerts:
1. Is this alert in SIMBAD? [`cdsxmatch`]
2. Is is this alert a Solar System Object? [`roid`]
3. Is this alert an early SN Ia? [`rfscore`, `snn_snia_vs_nonia`, `snn_sn_vs_all`, `classtar`, `ndethist`, `drb`]
4. Is this alert a SN Ia? [`snn_snia_vs_nonia`, `snn_sn_vs_all`, `classtar`, `ndethist`, `drb`]
5. Is this alert a microlensing event? [`mulens_class_1`, `mulens_class_2`]
if none, this alert is `Unknown`. If several, this alert is `Ambiguous`.
=> [Classification] Update the criteria to label alerts

apps/explorer.py
The initializer for RA/Dec is more flexible and supports inputs provided in a number of convenient formats. The following ways of initializing a conesearch are now all equivalent:
```bash
271.3914265, 45.2545134, 5 
271d23m29.1354s, 45d15m16.2482s, 5
18h05m33.9424s, +45d15m16.2482s, 5 
18 05 33.9424, +45 15 16.2482, 5
18:05:33.9424, 45:15:16.2482, 5
```
Note that the default frame is ICRS.
=> Add more units for the conesearch

apps/explorer.py, assets/home.css
This PR brings two major change in the explorer documentation:
- Help for each type of query is now accessible next to the query (#35 )
- A message is shown whenever the query returns no results, or is not allowed (e.g. multi index search) (#36 )
=> Improve documentation for explorer

index.py
This PR update the GitHub link to point to the Fink science portal instead of the broker (#29). The general layout of the home page is also improved.
=> Update GH link, and improve layout

apps/cards.py, apps/plotting.py
We now have one single callback instead of 3 to display cutouts. This prevents the client to crash.
=> Unify cutout callbacks

apps/explorer.py, apps/utils.py
#59 
Users can now add columns with the measurement of the last `r-g` and the `rate(r-g)`. 
There are some limitations though:
- `r-g` is measured from two measurements inside the same night. The displayed `r-g` is not from the latest measurement, but from the latest night from which we had at least two measurements. Hence keep in mind the displayed `r-g` can be a week old. You can check when this value was taken by looking at object data directly.
- When displaying data from latest class `C`, we query the database for alerts with classtag `C`. `r-g` and its rate are computed from this pool of results. Hence if an object has alert with different classtag, its `r-g` can be different than the one that would be derived from the full object data (since alerts with classtag `C` represent only …
=> [Explorer] add color evolution (r-g and its rate) in the explorer page

apps/api.py, apps/utils.py
This PR allows the user to select only a subset of columns to be transfered. Default is:
- object data retrieval: all columns (ZTF original + Fink science modules + Fink derived values)
- conesearch: a subset of ZTF original + all Fink science modules + all Fink derived values
- date search: a subset of ZTF original + all Fink science modules + all Fink derived values
- latest alerts: a subset of ZTF original + all Fink science modules + all Fink derived values
In addition this PR clean a bit the data manipulation before transfer.
=> Select alert fields to transfer

apps/utils.py
In that case, the classification is less constrained, but I checked it does not really introduce more objects.
=> Add Fail to the cdsxmatch categories for SN classification

apps/api.py
We do not currently support VOTable output format in the API, but we show how to easily get the output in voformat using the json serialisation
```python
from astropy.table import Table
'http://134.158.75.151:24000/api/v1/objects',
json={
'objectId': 'ZTF19acnjwgm',
'output-format': 'json'
}
)
t = Table(r.json())
```
=> Start to introduce VOTable

apps/api.py, apps/explorer.py, apps/utils.py
One of the big category of alerts concerns the Solar System Objects (SSO). They can represent up to 10% of the processed stream each night. They are different from other alerts as their brightness changes, but also their position on the sky. 
At the highest level, there are 2 types of SSO candidates: the alerts that are within 5'' of a reported objects in the Minor Planet Center (MPC) database, and the other alerts that pass Fink-specific cuts for SSO. We focus here on the first kind.
Among the MPC-known objects, there are two main types: asteroids and comets (no interstellar objects have been found in Fink so far). According to MPC, they can have either a number (best), or a designation (before being numbered). We handle both here.
The list of arguments for retrieving SSO data can be …
=> [API] Add Solar System Objects

apps/explorer.py
The class `Unknown` was missing from the Class Search dropdown menu in the Explorer page.
Closes #114
=> Add the Unknown class to the Class Search dropdown menu

apps/api.py, apps/utils.py
This PR enables to download cutout data from the REST API. This is only restricted to `objectId` query for the moment. You would simply do:
```python
import matplotlib.pyplot as plt
'http://134.158.75.151:24000/api/v1/objects',
json={
'objectId': 'ZTF19acnjwgm',
'withcutouts': 'True'
}
)
columns = [
'b:cutoutScience_stampData',
'b:cutoutTemplate_stampData',
'b:cutoutDifference_stampData'
]
for col in columns:
data = pdf[col].values[0]
plt.show()
```
See [here](https://github.com/astrolabsoftware/fink-science-portal/blob/1dea22170449f120d92f404ac20bbb856e1e77fc/apps/plotting.py#L584-L593) how we do in the Science Portal to display cutouts.
Note that you need to flip the array to get the correct orientation …
=> Enable cutout data transfer

apps/api.py, apps/plotting.py, apps/utils.py
This PR adds a new service to retrieve cutout data. 
The list of arguments for retrieving cutout data can be found at http://134.158.75.151:24000/api/v1/cutouts.
In a unix shell, you can retrieve the last cutout of an object by simply using
```bash
curl -H "Content-Type: application/json" \
-X POST -d \
'{"objectId":"ZTF19acnjwgm", "kind":"Science"}' \
http://134.158.75.151:24000/api/v1/cutouts -o cutoutScience.png
```
This will retrieve the `Science` image and save it on `cutoutScience.png`.
In Python, the equivalent script would be:
```python
import io
from PIL import Image as im
'http://134.158.75.151:24001/api/v1/cutouts',
json={
'objectId': 'ZTF19acnjwgm',
'kind': 'Science',
}
)
image = im.open(io.BytesIO(r.content))
image.save('cutoutScience.png') …
```
=> Cutout service: online!

apps/api.py, apps/explorer.py, apps/utils.py, assets/tns_types.csv
This  PR allows to search Fink data labelled in TNS (#123 ). In addition, this PR introduces some other modifications:
- the API service Class Search gets two new arguments: `startdate` and `stopdate`. You can search for alerts of a particular class between these dates.
- the class name for SIMBAD and TNS are now prefixed -- i.e. you would no more search for `Blazar` but `(CDS) Blazar`. All class  names are available at http://134.158.75.151:24000/api/v1/classes
Example of usage:
```python
'http://134.158.75.151:24000/api/v1/latests',
json={
'class': '(TNS) SN Ia',
'n': '100',
'startdate': '2021-03-01',
'stopdate': '2021-03-05'
}
)
```
There is no limit of time, but you will be limited by the number of …
=> Allow searching by TNS tag

apps/api.py
This PR updates the http://134.158.75.151:24001/api/v1/objects service by allowing the users to retrieve upper limits and bad quality data (as defined by Fink quality cuts) alongside valid measurements. For this, a new argument is available: `withupperlim` (see usage below). Note that the returned data will contained a new column, `d:tag`, to easily check data type: `valid` (valid alert measurements), `upperlim` (upper limits), `badquality` (alert measurements that did not pass quality cuts). Here is an example that query the data, and plot it:
```python
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context('talk')
'http://134.158.75.151:24000/api/v1/objects',
json={
'objectId': 'ZTF19acnjwgm', …
```
=> Enable querying upper limits and bad quality data

apps/explorer.py, apps/utils.py, assets/fink_types.csv
Following #135 and https://github.com/astrolabsoftware/fink-broker/issues/441, SSO are now categorized into 2 classes: known objects from MPC (`Solar System MPC`) and new candidates (`Solar System candidate`)
=> Update the frontend with new SSO classes

apps/api.py, apps/cards.py, apps/explorer.py, apps/plotting.py, apps/summary.py, apps/utils.py, assets/fink_types.csv, assets/simbad_types.csv
This PR adds a new bar that displays individual alert classification, e.g.:
The idea behind this bar is to help users to take a decision on what is the _object_ classification (so far, we were using only the last alert classification)
=> Add a bar to detail individual alert classification

apps/api.py, apps/explorer.py, apps/utils.py, apps/xmatch.py
This PR updates the conesearch & xmatch API. 
The new conesearch is now multiresolution: nside=128 (degree scale), nside=4096 (arcmin scale), nside=131072 (arcsec scale). For this purpose, a new index table was created, indexed on various nsides (plus the date). Note, with this implementation we can perform conesearch from arcsecond radius to degree radius within a minute. Here is a rough scaling:
Note that we limit the query to retrieve only the first 10,000 alerts (i.e. less objects). In practice, this happens when radius > 1 degree. Note also that if you target radius around 1000 arcsecond (17 arcmin), you better choose a radius slightly bigger to enter the degree scale map, and boost the query time (see the transition on the plot). The transition between arcmin and degree might change …
=> Update the xmatch API

apps/cards.py, apps/summary.py
This PR adds 3 links in the Science Portal to the SNAD (ZTF-DR4) viewer:
- In the `Summary` view of an object for the desktop/laptop application
- In the `Variable Star` view of an object for the desktop/laptop application
- In the External tab of an object for the mobile application
Each button will redirect to a conesearch in the SNAD viewer, centered on the coordinates of the object, and with a radius of 5 arcseconds:
@emilleishida @hombit
=> Add links to the SNAD viewer

app.py, apps/api.py, apps/plotting.py, apps/summary.py, index.py
The idea is to preview alerts when querying the database.
There are some caveats:
- This is limited to the first 10 alerts because we have to download the data a posteriori (it is not loaded as you scroll).
- We show only the Science cutout (for the same data download reasons)
- The lightcurve is not shown in the mobile version because the display is not great (too squeezed).
=> Add a preview of table results in the Explorer page

apps/cards.py, apps/plotting.py, apps/summary.py
This PR adds a new button to inspect alert properties, and re-organise the `download` button. The display is now:
=> Add a new modal to display alert properties

apps/api.py
This PR introduces a new service to get all alerts falling inside a given LIGO/Virgo credible region sky map. The user simply upload the sky map with a threshold, and Fink returns all alerts emitted within `[-1 day, +6 day]` from the GW event inside the chosen credible region. Concretely on S200219ac:
```python
fn = '/Users/julien/Downloads/bayestar.fits.gz'
credible_level = 0.9
data = open(fn, 'rb').read()
'http://134.158.75.151:24000/api/v1/bayestar',
json={
'bayestar': str(data),
'credible_level': credible_level,
'output-format': 'json'
}
)
```
You will get a Pandas DataFrame as usual, with all alerts inside the region (within `[-1 day, +6 day]`). Here are some statistics on a random event:
| `credible_level` | Sky area | number of …
=> [GW] add a new API service to query alerts falling inside LIGO/Virgo probability sky maps

apps/api.py, apps/utils.py, index.py
This PR allows to query Fink via an URL. Some example:
```
https://fink-portal.org/?query_type=objectID&objectID=ZTF21abfmbix
```
```
https://fink-portal.org/?query_type=Conesearch&ra=193.822&dec=2.89732&radius=5&startdate_conesearch=2021-07-01 05:59:36&window_days_conesearch=1
```
Note that `startdate_conesearch` and `window_days_conesearch` are optional.
```
https://fink-portal.org/?query_type=Date Search&startdate=2020-07-01%2005:59:36&window=1
```
```
https://fink-portal.org/?query_type=SSO Search&n_or_d=4209
```
=> Query Fink by URL

apps/api.py, apps/plotting.py, apps/statistics.py, index.py
This PR adds a new page to gather various statistics about Fink data. It contains 3 tabs:
- heatmap
- daily statistics
- timelines
A fourth one will join later concerning TNS confirmed data.
The `Heatmap` tab shows the number of alerts processed by Fink for each night
since the beginning of our operations (2019/11/01). The graph is color coded,
dark cells represent a low number of processed alerts, while bright cells represent
a high number of processed alerts.
The `Daily statistics` tab shows various statistics for a given observing night. By default,
we show the last observing night. The first row shows histograms for various indicators:
- Quality cuts: difference between number of received alerts versus number of processed alerts. The difference is simmply due to the quality cuts in …
=> Add a new page with statistics

apps/statistics.py
It is rather difficult to display plots and use them on a mobile device. Therefore the mobile version of the statistics page is light, and contains only basic statistics:
=> [Stats] Mobile version

apps/summary.py
Closes #241
Without the fix:
With the fix:
=> Force column width for the SSO layout

apps/about.py, apps/api.py, apps/cards.py, apps/home.py, apps/plotting.py, apps/statistics.py, apps/summary.py, apps/utils.py, index.py, requirements.txt
**IMPORTANT: Please create an issue first before opening a Pull Request.**
Linked to issue(s): Closes #245  
This PR replaces all
```python
from fink_broker.science import extract_fink_classification
```
by
```python
from fink_filters.classification import extract_fink_classification
```
Note: needs recent fink-filters versions (1.0+).
None
=> [Classification] Use new location in fink-filters

app.py, apps/api.py, apps/cards.py, apps/plotting.py, apps/summary.py, assets/fink_types.csv, index.py
Closes #203 
This PR exposes tracklet data to the users. A tracklet is a set of spatially connected alerts (typically belonging to the same exposure) from a fast moving object. This is somehow similar to solar system object, expect that these objects are mainly man-made and they typically orbit around the Earth. The tracklet data can be accessed in different ways:
- search by class
- search for tracklets
more information at https://fink-portal.org/api.
Tracklets are an object class like the other classes. Hence you can look for these using the class search:
In the API you would just use:
```python
'https://fink-portal.org/api/v1/latests',
json={
'class': 'Tracklet',
'n': '100'
}
)
```
Look for the column …
=> Add support for satelitte glints and space debris

apps/api.py, apps/plotting.py, tests/api_performance_test.py
Closes #282 
If a query returns many objects, the computation of color slows down enormously the query execution time. For 20,000 objects one goes from 15 seconds to more than 180 seconds (timeout error).
It is available only when using the `objects` endpoint.
=> Speed up query performances by disabling color computation

apps/api.py, tests/api_single_object_test.py
Closes #291 
Now one can query the data for many objects at the same time:
```python
import numpy as np
'https://fink-portal.org/api/v1/objects',
json={
'objectId': 'ZTF19acmdpyr,ZTF21aaxtctv',
'withupperlim': 'True'
}
)
n_oids = len(np.unique(pdf.groupby('i:objectId').count()['i:ra']))
```
The argument is a comma-separated list of ZTF object IDs.
Todo:
=> Allow multi-object search

apps/utils.py, tests/api_classsearch_test.py
Closes #293 
Check if `i:jd` exists before sorting or grouping.
=> Check if jd exists before sorting or grouping

apps/api/api.py, apps/api/utils.py, apps/utils.py, assets/simbad_types.csv, index.py, tests/api_single_object_test.py
Closes #311 
This PR introduces a number of things on the Science Portal:
- A new button that gives the capability to group by alerts by name to only output a list of unique names. The last alert (in time) is kept.
- A new column `v:firstdate` which is the human readable datetime for the first variation of the object (from `i:jdstarthist`)
- A new column `v:lapse` which is the number of days between first and last detection.
Limitation: once the grouping by alert name is performed, one cannot go back to the full list (the table is overwritten). In order to get full results, the query needs to be re-ran.
One can  easily then filter results by their age by adding `v:lapse` and sorting:
The API is untouched, although new columns are available in the results (only when transferring all …
=> Group by alerts to get unique list

index.py
Sometimes, the reported name in SIMBAD is not completely correct (either an old label, or the 3-digit code instead of the long label) -- in this case we assign a specific class when displaying on the sky map.
Closes #344
=> Handle fake names from SIMBAD

apps/query_cluster.py
The column `classId` was containing `null` that were casting the type to `float` in some circumstances.
=> New path to elasticc data

app.py, apps/api/api.py, apps/api/doc.py, apps/api/utils.py, tests/api_anomaly_test.py
Closes #450 
This endpoint gets data from the `ztf.anomaly` HBase table. Each night, this table receives 10 alerts with the most anomalous scores. This table has full _alert_ schema, and you can easily gets statistics:
```python
import io
'https://fink-portal.org/api/v1/anomaly',
json={
'n': 10000, # on purpose large
'columns': 'i:objectId,d:cdsxmatch,i:magpsf'
}
)
pdf = pd.read_json(io.BytesIO(r.content))
pdf.groupby('d:cdsxmatch').agg({'i:objectId': 'count'}).sort_values('i:objectId', ascending=False)
i:objectId
d:cdsxmatch              
CataclyV*             191
Unknown               170
Mira                   65
RRLyr                  63
LPV*                   52
EB*_Candidate          21
EB*                    20
Star …
```
=> [API] Endpoint to retrieve anomalous alerts

app.py, apps/cards.py, apps/plotting.py, apps/summary.py, apps/utils.py
This PR brings two modifications:
- Flux is in (milli)Jansky now
- If a point source is detected behind the alert, we warn the user that DC magnitude are more relevant
In addition, lightcurve documentation has been updated. This PR does not solve all, and more needs to be added later (especially see discussion in #446)
=> Put flux units in Jansky & warn users about magnitude units

apps/plotting.py
Closes #443 
Note that in rare cases, the layout is bizarre, e.g.
but this only happens when database jobs have failed to push previous night data (because there should not be upper limits without a more recent valid point). At least, this will warn us that something fishy is ongoing!
=> Merge traces from the same band

app.py, apps/api/api.py, apps/api/utils.py, requirements.txt, tests/api_resolver_test.py
This PR introduces a name resolver (see #476 ). Names can be resolved in 3 different ways: 
1. using SIMBAD (Sesame service)
2. using SSODNET (for asteroids)
3. using TNS
For all, there is also a reverse resolver, that is given a ZTF objectId, what is the match in these catalogs. Note that SSODNET and TNS allow auto-completion, but not SIMBAD.
```python
'https://fink-portal.org/api/v1/resolver',
json={
'resolver': 'tns',
'name': 'SN 2023',
'nmax': 10
}
)
```
=> Name resolver

assets/spark_elasticc_transfer.py, tests/api_resolver_test.py
With the recent change when generating the data schema (#471), some fields were not correctly casted before the distribution. This PR fixes this (only for Elasticc data source).
=> Cast fields before transfering data

apps/plotting.py
The effect was only on the display -- values returned by the API were correct.
Before:
After:
=> Convert alpha0 and delta0 in radians before plotting

index.py
Idea is to have most important pages directly accessible without additional clicking.
Points for discussion:
- Burger menu moved to the right to somehow fill that emtpy spot (sidebar still opens on the left). Probably when authentication will be implemented the avatar / user menu would go there, and the burger will return to leftmost slot.
- Do we need Fink logo in the leftmost spot? Would probably visually conflict with current 'search' entry. 
- Small shadow is added for the whole header to slightly better separate it from the page content. Probably will need some adjustment when backgrounds are changed.
=> Add responsive menubar to complement current togglable sidebar.

apps/api/api.py, apps/api/doc.py, apps/api/utils.py, tests/api_resolver_test.py, tests/api_ssocand_test.py
A new HBase table has been added (https://github.com/astrolabsoftware/fink-broker/pull/774) to enable resolving SSO names more easily. The resolver behaviour for `ssodnet` has been modified (syntax remains the same). You'll find below some typical use cases.
I have a SSO name or number, are there ZTF objects corresponding?
You first need to resolve the corresponding ZTF `ssnamenr`:
```python
'https://fink-portal.org/api/v1/resolver',
json={
'resolver': 'ssodnet',
'name': '624188'
}
)
pdf = pd.read_json(io.BytesIO(r.content))
i:name  i:number i:ssnamenr
0  2002 MA6    624188    2002MA6
1  2002 MA6    624188     624188
2  2002 MA6    624188   2002MA06
3  2002 MA6    624188     624188
```
and then search for corresponding alerts for all `ssnamenr`:
```python
r = …
```
=> Improve SSO resolver

app.py, apps/cards.py, apps/plotting.py, apps/summary.py, apps/utils.py
Adds an option to request and display the photometry from ZTF data releases (IRSA archive) in the DC magnitudes tab of lightcurve panel. Also, shows the levels of magnr in the same tab, to be able to quickly see how much alert points actually deviate from it. The lines are not toggleable, as Plotly does not support it yet (implemented through shapes, not traces). These line plotting, and DC mag conversion in general, happen only when the nearest object is close enough (1.5 arcsec by default), i.e. when the alert is shown. The resulting DC magnitudes are also filtered to hide the points with errors exceeding 1 mag (basically, not measured), in order to make the plot more resistant to bad quality points.
Finally, some cleanup and visual simplification (e.g. removal of errorbar caps, and …
=> Data release photometry for lightcurve panel

app.py, apps/api/api.py, apps/api/doc.py, apps/api/utils.py, apps/cards.py, apps/gw.py, apps/parse.py, apps/plotting.py, apps/query_cluster.py, apps/statistics.py, apps/summary.py, apps/utils.py, assets/home.css, assets/theme.css, index.py, tests/api_conesearch_test.py
Redesign of the search page to use "smart search" like in Google or ADS. Like the latter, offer the palette of search terms above the input field. 
Possible queries are like:
- `10 20 300` - cone search at ra=10 dec=20 with 300 arcsec radius
- `Vega r=10` - cone search within 10 arcsec around Vega
- `10 20 300 after="2023-01-01" window=1` - cone search within 300 arcsec from Vega in 24 hours after given moment
- `ZTF22abzanvj` - exact search for objectId
- `ZTF23abshpmf r=100` - cone search within 100 arcsec around the alert
- `ZTF22abzan` - partial match search for objectIds starting with given pattern
- `TRCK_20231212` - partial match search for tracklets (effectively, all tracklets from a given date)
- `class=Unknown` - last 100 alerts of a given class
- `class=Unknown last=10` - last …
=> Improvements for the search page

apps/plotting.py, apps/supernovae/cards.py
Fixes #560 , and is a client-side alternative to #564 
Does not take into account T2 plots (I never saw one, so don't know whether they are even relevant)
=> Clientside linked zoom (x axis only) for SN plots

apps/api/api.py, tests/api_anomaly_test.py, tests/api_bayestar_test.py, tests/api_classsearch_test.py, tests/api_columns_test.py, tests/api_conesearch_test.py, tests/api_cutouts_test.py, tests/api_datesearch_test.py, tests/api_euclidsso_test.py, tests/api_performance_test.py, tests/api_random_object_test.py, tests/api_resolver_test.py, tests/api_single_object_test.py, tests/api_sso_test.py, tests/api_ssocand_test.py, tests/api_ssoft_test.py, tests/api_stats_test.py, tests/api_tracklet_test.py, tests/api_xmatch_test.py
Closes #578 
This PR updates the schema definition in `api/v1/columns`. This PR also adds new checks for alert columns:
- check that recent alerts have all columns defined in /api/v1/columns
- check new fields added compared to old alerts
This PR also updates existing tests by being more explicit if an API request fails.
=> Stricter checks on alert columns

apps/summary.py
Closes #617 
Note: this is still computed at the API level (`apps/api/utils.py`)
=> Do not compute ecliptic coordinates for SSO

apps/api/api.py, apps/api/utils.py
This PR brings speed up in downloading the SSOFT in parquet format
| output format | download time |
|-------------------|---------------------|
| csv | 21.28 seconds |
| json | 16.61 seconds |
| parquet (old) | 5.85 seconds |
| parquet (new) | 4.84 seconds |
`json` and `csv` are slow because the data needs to be decompressed, and formatted in pandas DataFrame before being sent to the user (that is: DO NOT USE THAT unless you really needs it). The parquet mode is now faster because I get rid of the pandas DataFrame step.
=> Faster SSOFT download

apps/api/api.py, apps/api/doc.py, apps/api/utils.py, apps/utils.py, tests/api_single_object_test.py, tests/api_sso_test.py
There is now a new argument `withcutouts` to `api/v1/sso` to include stamps data when querying a Solar System object:
```python
'https://fink-portal.org/api/v1/sso',
json={
'n_or_d': '8467',
'withcutouts': True,
'output-format': 'json'
}
)
r.json()[0]["b:cutoutScience_stampData"]
[[123.70613861, 125.00068665, 129.01676941, ..., 123.77194214,
130.44299316, 106.22817993],
[121.61331177, 128.18247986, 124.99162292, ..., 115.30529785,
129.93824768, 100.24826813],
[124.31635284, 134.16503906, 125.13191223, ..., 131.05186462,
116.30375671, 102.97401428],
...,
[133.20661926, 123.14172363, 121.78632355, ..., 132.95498657,
131.95939636, 111.22276306],
[129.26271057, 127.34268188, 123.1470108 , ..., 126.02961731,
128.23413086, 107.28420258],
[126.06323242, …
```
=> Access stamps data when querying Solar System objects

apps/parse.py
Closes #648 
In the case of a conesearch in the form `h:m:s d:m:s`, the [regex](https://github.com/astrolabsoftware/fink-science-portal/blob/363511ac5c2287a71851ba2289b7879c6f4a2c7e/apps/parse.py#L187) `^(\w+)[=:](.*?)$` was interpreting the left side of the first occurence of `:` as a valid key:
```python
{'object': None, 'type': None, 'partial': False, 'hint': None, 'action': None, 
'params': {'18': '45:05.2'}, 'completions': [], 'string': '18:45:05.2 -63:57:47.4'}
```
This PR adds a guard against numeric keys found, assuming they reflect the start of a conesearch of the form `h:m:s d:m:s` (I do not think having a numerical key can happen in another query context?).
---
**Note**: explicitly specifying `RA=h:m:s DEC=d:m:s` still does not work, as the parser recognises correctly `ra` and …
=> [searchbar] Enable conesearch with h:m:s d:m:s

apps/sso/cards.py, apps/summary.py
=> SSO: update information

apps/api/api.py, apps/api/utils.py, requirements.txt, tests/api_ssoft_test.py
Enable the download of SSHG1G2 from the API. The web portal is not yet updated.
=> SSHG1G2 in the API

apps/query_cluster.py
Closes #699 
@FusRoman -- bug due to the renaming of an object in a new version of dmc #694
=> Rename DatePicker into DatePickerInput (dmc>=0.15)

apps/__init__.py, index.py
This PR does:
- replace occurrences of /explorer. 
- remove the `daterange` action from query URL (search by date is no more allowed with the new API)
- fix type issue when searching in history menu
=> Remove the use of the explorer endpoint

apps/plotting.py, apps/varstars/cards.py
This PR removes the use of `gatspy` which was unmaintained, and replace it by astropy functionalities. In addition, we use `nifty-ls` in the backend for `nterms=1` (the default configuration) to benefit from huge speed-up. Fitting for the period on an object with 2 bands, hundreds of measurements per band, is a matter of a couple of seconds.
=> Switch to astropy LombScargle implementation for varstar

apps/cards.py
I was wrong in #750 -- the endpoint `/metadata` uses POST.
=> Re-use POST for metadata

apps/summary.py
As we have more tabs now, it is time to hide non-relevant ones instead of just greying them out.
Big question - is the "Observability" tab relevant for all object types?.. I am thinking about disabling it at least for tracklets, probably - for SSOs also. Basically - for the ones where position is changing, so observability prediction based on alert coordinates is probably not very useful.
=> Hide non-relevant tabs in summary view
